allowBuilds:
  '@clerk/shared': true
  esbuild: true
  sharp: true

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - sharp
  - tree-sitter
  - tree-sitter-json
  - '@esbuild-kit/core-utils'

overrides:
  esbuild: '>=0.25.0'
  parse5: ^7.1.2
  '@opentelemetry/api': 1.9.0
  '@tiptap/core': 3.22.3
  '@tiptap/pm': 3.22.3

packages:
  - "apps/*"
  - "packages/*"
