/**
 * PR 12 PR 3: TanStack Query wrappers for the student-facing onboarding
 * status page. Mirrors the pattern used by `use-admin-onboardings.ts`:
 * convex query keys generated by `@convex-dev/react-query`, types
 * inferred from the generated `api` surface.
 */
import { useQuery, UseQueryResult } from "@tanstack/react-query";
import { convexQuery } from "@convex-dev/react-query";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import type { OnboardingStatus } from "@/lib/admin-onboarding";

export type { OnboardingStatus };

export type OnboardingViewPerInstructor = {
  _id: Id<"instructors">;
  name: string | null;
  slug: string | null;
  isRenewal: boolean;
};

export type OnboardingViewTimelineEntry = {
  at: number;
  event: string;
  actorUserId?: string;
  details?: string;
};

export type OnboardingView = {
  onboarding: {
    _id: Id<"adminOnboardings">;
    email: string;
    status: OnboardingStatus;
    createdAt: number;
    attemptCount: number;
    failureReason: string | undefined;
    assignedStudentClerkId: string | undefined;
  };
  viewerRole: "student" | "instructor" | "admin" | "support";
  instructors: OnboardingViewPerInstructor[];
  timeline: OnboardingViewTimelineEntry[];
  timelineOlderCount: number;
};

/**
 * TanStack Query wrapper around
 * `convex.onboardingViews.getOnboardingView`. Returns `null` when the
 * row is missing OR the caller isn't authorized (student match, admin,
 * support, or matching instructor). The status page renders a 404 in
 * both cases to avoid existence leakage.
 */
export function useOnboardingView(
  id: Id<"adminOnboardings"> | null | undefined
): UseQueryResult<OnboardingView | null, Error> {
  return useQuery({
    ...convexQuery(
      api.adminOnboarding.getOnboardingView,
      id ? { onboardingId: id } : { onboardingId: "" as Id<"adminOnboardings"> }
    ),
    enabled: !!id,
  });
}

/**
 * Tanstack Query wrapper around
 * `convex.adminOnboarding.getIncompleteOnboardingForCurrentUser`.
 * Returns the most-recent non-terminal onboarding row for the
 * currently signed-in student, or `null` if there isn't one. Drives
 * the post-signup redirect decision in `sign-up-redirect` and
 * `auth-redirect`.
 */
export function useIncompleteOnboardingForCurrentUser(): UseQueryResult<Id<"adminOnboardings"> | null, Error> {
  return useQuery(convexQuery(api.adminOnboarding.getIncompleteOnboardingForCurrentUser, {}));
}
