/**
 * Database types for Supabase
 * 
 * This file will be auto-generated by Supabase CLI:
 * npx supabase gen types typescript --project-id <project-id> > src/types/database.types.ts
 * 
 * For now, we'll use a basic type that matches our schema structure.
 * You should regenerate this file after setting up your Supabase project.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          role: "student" | "mentor" | "admin";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          role?: "student" | "mentor" | "admin";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          role?: "student" | "mentor" | "admin";
          created_at?: string;
          updated_at?: string;
        };
      };
      mentors: {
        Row: {
          id: string;
          user_id: string;
          max_active_students: number;
          bio: string | null;
          pricing: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          max_active_students?: number;
          bio?: string | null;
          pricing?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          max_active_students?: number;
          bio?: string | null;
          pricing?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      // Add other tables as needed
      // This is a simplified version - regenerate with Supabase CLI for full types
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: "student" | "mentor" | "admin";
      order_status: "pending" | "paid" | "refunded" | "failed" | "canceled";
      payment_provider: "stripe" | "paypal";
      payment_status: "pending" | "completed" | "refunded" | "failed";
      session_pack_status: "active" | "depleted" | "expired" | "refunded";
      seat_status: "active" | "grace" | "released";
      session_status: "scheduled" | "completed" | "canceled" | "no_show";
    };
  };
}

